### PR TITLE
node graph cleanups

### PR DESCRIPTION
**Pull request by ecsv**
Fixes the down graph problem as described in issue #83 and the overlapping labels problem for nodes with many clients from issue #84

### CODE REVIEW

**Comment by jplitza** [comment]
Merged the part that corresponded to #84.

Did you test the part for #83 with high-resolution graphs as well? I applied it and notice that all the graphs now show the node as down during the current hour ([example](http://downloads.bremen.freifunk.net/data/nodes/10feede5fb22.png)).

**Comment by ecsv** [comment]
I have the problem of nodes showing as down for the current time since a long time (before even thinking about the changes from #83).

**Comment by ecsv** [comment]
I have now modified the code to assume that undefined upstate means that the node is running:

<pre>
if !defined(upstate):
   upstate = 1

if upstate == 0:
   t = 1

if !defined(maxc):
    maxc = 1

maxc = max(1, maxc)

d = t * maxc
</pre>

This is now a different interpretation but should avoid that the "down" region at the current time

**Comment by ecsv** [comment]
Closing this because we are not using it anymore and there was no reaction anymore from upstream

**Pull request closed without merging**
