### PR TITLE
Don't assume "hostname" is present

### PR DESCRIPTION
**Pull request by kpcyrd**
https://forum.freifunk.net/t/meshviewer-zeigt-ploetzlich-typeerror/6956

### CODE REVIEW

**Comment by tcatm** [comment]
I don't think setting "unnamed" as a default is sane. Could this work without a hostname at all?

**Comment by kpcyrd** [comment]
Leaving `name` unset would be another way, but I think this would potentially break a lot of other things.

**Comment by tcatm** [comment]
A quick solution may be to ignore such nodes (as is done for nodes with bogus coordinate information).

**Comment by mweinelt** [comment]
I'm not sure such a generic try/except is necessary, we're talking about the hostname in this pull request only, aren't we? Also: You should probably rebase your code on top of HEAD, instead of dragging along 10 other commits from other people.

**Comment by kpcyrd** [comment]
@mweinelt maybe stop rewinding head then? master was pointing to `c2e21b4` at the point I've forked the repo. `275d6e4` was my original proposal to fix the bug, feel free to PR a better solution.

**Pull request closed without merging**
