### PR TITLE
sanity check for node_id

### PR DESCRIPTION
**Pull request by Sunz3r**
if node_id contains invalid characters then the script stop working

### CODE REVIEW

**Comment by jplitza** [comment]
Not generating for "strange" node_ids is obviously suboptimal. What exactly causes what to stop? Can we fix it by replacing "strange" characters?

**Comment by Sunz3r** [comment]
Characters like : stops working the script. You can inject code with the node_id therefore replacing characters are not needed because this should only prevent errors.

**Comment by tcatm** [comment]
Please don't use non-alphanumeric characters in your node id (I have changed my mind about this, in case you're reading older issues about this topic). This is a won't fix.

**Comment by Sunz3r** [comment]
You wont fix a possible secuity issue? Everyone can break this script by send bad node_ids.
Maybe i blog a warning about this problem so we dont need to fix this if everyone knows about it?

**Comment by tcatm** [comment]
Well, I may accept a PR that simply rejects nodes with invalid data. This PR, however, introduces some strange undocumented behaviour that may cause more trouble than harm.

This would be the right place to implement it:
https://github.com/ffnord/ffmap-backend/blob/master/lib/validate.py

**Comment by Sunz3r** [comment]
Thanks, i just push another PR with proper implementation :)

**Pull request closed without merging**
