### PR TITLE
Make the json outputs diffable by sorting its keys

### PR DESCRIPTION
**Pull request by mweinelt**
This enables the use of diff to compare the output files.

### CODE REVIEW

**Comment by flokli** [comment]
:+1:

**Comment by jplitza** [comment]
Diffing output files seems like an unusual usecase, and sorting the keys has no advantage for the usual usecases like lists and maps of nodes. Is it worth sorting the keys on *every generation* rather than sorting them on demand when you want to compare files? (Piping through `jq -S .` would do exactly that)

**Comment by flokli** [comment]
@jplitza sure, one could also sort them on demand. But it doesn't really hurt to already serve them sorted, so why not?

**Comment by jplitza** [comment]
I still have a bit of stomach pain by using CPU cycles for something rarely used, but what the hell…

**Pull request merged**
