### PR TITLE
Added traffic to Statistics

### PR DESCRIPTION
**Pull request by stebifan**

### CODE REVIEW

**Comment by tcatm** [comment]
I'm not sure whether adding this data verbatim is of much use. Should we do some preprocessing?

**Comment by stebifan** [comment]
We use this data to display the Traffic of each node. I don't need it upstream, but i thought that it could be  usefull for other communitys.

**Comment by tcatm** [comment]
What are you using this data for? We could work on a format that is useful for many communities.

**Comment by xeaon** [comment]
atm we are using alfred_merged.json as information source for http://fmon.freifunk-troisdorf.de because of missing traffic data in nodes.json. with this commit we should be able to replace the source.

**Pull request merged**
