### PR TITLE
add firstseen to nodelist.json

### PR DESCRIPTION
**Pull request by kantorkel**
I need the firstseen attribute for a new-node-tweet-bot.

### CODE REVIEW

**Comment by tcatm** [comment]
I can not find the field "firstcontact" in the []nodelist specification](https://github.com/ffansbach/nodelist). Please add the field there first.

**Comment by kantorkel** [comment]
The firstcontact field has been added: https://github.com/ffansbach/nodelist/commit/db283538ac438cbe7184b2407bc0bf48706deed6

**Comment by tcatm** [comment]
Great. Could you fix the whitespare errors Travis CI is complaining about?

**Comment by kantorkel** [comment]
done.

**Pull request merged**
